Test client build.
EdgePi-Cloud/edgepi-rpc-client-py pull request #25
Opened 2023-10-03 22:35 UTC by josiah-tesfu

Write an integration test to test the client build. After some minor fixes, the test passes.

As a sanity check, I ran the test on an older branch that had the previous directory structure (before the proposed change of moving all modules under `edgepi_rpc_client` while only importing the services in `setup.cfg`) and it failed under the same condition as the integration tests on the server repo currently fail.

2023-10-03 23:00 UTC, farzadpanahi approved these changes

2023-10-03 23:00 UTC, farzadpanahi requested changes

2023-10-03 23:00 UTC, farzadpanahi commented on tests/integration/test_module.py
enable integration test workflow.

2023-10-04 00:22 UTC, farzadpanahi requested changes

2023-10-04 00:22 UTC, farzadpanahi commented on tests/integration/integration_inactive/conftest.py
I think `integration_inactive` should be under `tests` not `integration` otherwise when you run pytest against integration folder, it will also run the inactive tests

2023-10-04 01:16 UTC, naomiven approved these changes, later dismissed
looks good

2023-10-04 01:16 UTC, naomiven commented on tests/integration/integration_inactive/__init__.py
why do you have this `integration_inactive` dir? is there a reason you are skipping these tests?

2023-10-04 17:40 UTC, farzadpanahi approved these changes, later dismissed

2023-10-04 17:40 UTC, farzadpanahi commented on tests/integration/conftest.py
do you need to comment out this file? I think this test will not run right now because you only have test_module in the workflow, right?

2023-10-04 18:18 UTC, josiah-tesfu commented on tests/integration/conftest.py
`conftest.py` still runs even with the limited scope.

2023-10-04 18:30 UTC, farzadpanahi approved these changes

2023-10-04 18:59 UTC, josiah-tesfu commented on tests/integration/integration_inactive/__init__.py
That was a temporary thing. It's gone now.

2023-10-04 19:00 UTC, merged